#!/bin/sh
export LD_LIBRARY_PATH="/app/PiliPlus/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export LD_PRELOAD="/app/lib/piliplus/libpiliplus-appindicator-shim.so${LD_PRELOAD:+:$LD_PRELOAD}"
export XCURSOR_PATH="/run/host/user-share/icons:/run/host/share/icons${XCURSOR_PATH:+:$XCURSOR_PATH}"

exec /app/PiliPlus/piliplus "$@"
